### ISSUE TITLE
Dynamic Resizing

### ISSUE THREAD

**Issue by nsaronson** [maml/SVGPlayButton#4]
Hello, I am using this button in my project, and when I try and use constraints to resize the play button, the view frame shifts (I can see this in view debugging), but the button remains on the top left of its view frame and does not resize. How can I fix this?

**Comment by nsaronson** [comment]
<img width="105" alt="screen shot 2016-04-20 at 2 24 51 pm" src="https://cloud.githubusercontent.com/assets/12642983/14685732/b3e3fb66-0703-11e6-8aef-a3d76e5c885a.png">

This is what it looks like.

`NSLayoutConstraint(item: playButton, attribute: .Width, relatedBy: .GreaterThanOrEqual, toItem: platformView, attribute: .Width, multiplier: 1/2, constant: 0)` is the code I am using for the constraint. In the image I posted, the constraint is active, that is why the yellow frame is larger.

**Comment by nsaronson** [comment]
I am using a single instance of this play button on my playing controller, which has 2 view sizes.

In view size 1, `NSLayoutConstraint(item: playButton, attribute: .Width, relatedBy: .GreaterThanOrEqual, toItem: platformView, attribute: .Width, multiplier: 1/2, constant: 0)` is active.

In view size 2, `NSLayoutConstraint(item: playButton, attribute: .Width, relatedBy: .GreaterThanOrEqual, toItem: songArtView, attribute: .Width, multiplier: 1/2, constant: 0)` is active.

Between transitioning between the views, I remove the playButton from one view, deactivate all constraints, and then re-add it to the other.

I know that the constraints are doing as they are supposed to, because the view frame is changing but the button images are not dynamically re-drawing themselves.

**Comment by maml** [comment]
For this situation I'd try calling layoutIfNeeded() on the parent view of the button after it's been re-added.

**Comment by nsaronson** [comment]
That doesn't work for me. Later this afternoon I can put together a small project that simulates what I am doing, in terms of movement, so you can look and see directly.

**Comment by nsaronson** [comment]
Here is a sample project.

https://github.com/nathanandersen/SVGFrameShiftDemo

**Comment by nsaronson** [comment]
You can clone/run that project, and press the two buttons to see an illustration of the behavior I am experiencing.

**Comment by maml** [comment]
Thanks for posting the sample project. I cloned the repo, ran it locally on a simulator, and was able to reproduce the symptoms you described. I don't think this an issue with the button but rather has to do with how it's being used in this particular case.

What I noticed is that I can get the button to honor the constraints for the separate subviews it's added to by telling it that it's bounds rect needs to be redrawn (via `setNeedsDisplay()`). For your example you should call that on the button instance after it's been added to a subview and had its constraints reactivated. I don't think calling `updateConstraints()` (on the button) or `layoutIfNeeded()` (on its parent view) are necessary.

From my understanding, the reason `setNeedsDisplay()` does the trick is because that tells the view to redraw itself in it's bounds rectangle, which in turn will cause its `drawRect:` method to fire. `drawRect:` is where this particular button creates and positions all of its visible pieces so without doing anything that causes it to fire that method, it'll probably never look how you'd expect for your particular use case. Hope this helps.

**Comment by maml** [comment]
Here's a screen grab of my fix for your sample project.

![demo-fixx](https://cloud.githubusercontent.com/assets/120183/14693805/02b9a03c-0728-11e6-8f44-26a017a1f905.gif)

**Comment by nsaronson** [comment]
Many thanks for your time.

**Comment by maml** [comment]
You bet! Glad this is potentially useful to you.

FYI I'm going to mark this as invalid as technically it's not an issue with the button itself although your feedback's great in helping me improve documentation about its implementation and behavior.
